language: node_js
node_js:
- '0.12'
sudo: false
before_script:
- npm install -g gulp
- npm install -g codeclimate-test-reporter
- gem install scss-lint -v 0.38.0
- gulp preprocess
- cd examples/server && npm install && cd ../..
script:
- npm test && gulp e2e
after_success:
- gulp coveralls
- codeclimate < coverage/lcov.info
- |
  if [ "$TRAVIS_BRANCH" = "master" ]; then
    git config credential.helper "store --file=.git/credentials"
    echo "https://${GH_TOKEN}:@github.com" > .git/credentials
    git config --global user.name "Grommet Community Bot"
    git config --global user.email "asouza@hp.com"
    gulp release:stable
    curl -X PUT -s -d '{"passed": true}' -u ${SAUCE_USERNAME}:${SAUCE_ACCESS_KEY} https://saucelabs.com/rest/v1/${SAUCE_USERNAME}/jobs/${TRAVIS_JOB_ID}
  fi
env:
  global:
    - secure: TIpFQ9neUyaM8wSydTnN00Tg1/iZH6gkbZsX45HYNugVA37NzSEzHB6n+dA6ZJzY8gaMFVf62MqNAngQLh9pdyqbt2NwQ0zmYqGIe77Xzxa7hvBzogL+Cvook+0kQh/OORj2VFxnfIXlC9On8Tpgv6f3gnbNDDxIxJHhux+8viD23XQMpYvyY2y14/8K9UrrdnbBchX0L+7BVASUUatvF7UuQ2R424WqoSp72XfUDpJ5uX+lKAMsaLGXQvK9h8RqE8ZtSaAD0pg1/bBgsxryZMNGH+0gUWZJDgLTyocLyS6oDamgyx0JR6rXqEtv+Z9kDQPspYwd0fsoMivcXLImPFp/lCLWosuGNCJG61Rzdjl44dxnjgYmEwg1+siwZbbhSzh4UdVqkjUPmFT7rezrU1I/PGEhS1jNcZSFu24shatJXWYDXNEFsqURICPrKyP13UaNOc4utRhxvOqzIQyBUPtJKwORFRsMwQS3x/Q3UvCpeGpF1swR2F/TWijre4H/tuoRw79qe1UDKrEmT88uAFXy3ggA+D3MDOUal3DqAx2dp7kB5f2wyo0hgp6nbTXEtZYkvfy2u6IQU1bukEsUpc+h03If4WxXyNe6nMzxdGvJC7qWhscHNDlP6Q9jatifUdLUL0UESWC7c/xwt6L3u2hJuq3Y09QpzMe4tkaOHBw=
    - secure: lqGLksD68NJvxZ9mvi9ghSQBI7FUC48/ioXyoRm62fsu1b3h1F7M5OPKsNaMcDtNfsJJc8DieDZmsjOH6IJeBGNNK4zQ36PvXlUzNeIF1QgaFsUw1MS9boG8pyEGQ58Uy/1otgOFwOGfnob9PsUReEhLmPX/5M9HU7gen6ZXi3P1cirR0r9d5Aaw4SvsU+IO/iIEw2k2IUTkNst620faBUMWHY5i/3TGrEqryJOIdvq7pQoVADBOvVtZhTCy1+1Hzw0Xghj+LpoliW3/7MlmhNmtVuyae0s9Bo8rvgYeYiIqArj8A6+0OGvnn6rrxP3+v2LTbABzHWX3Gj45JFLJteytpctatDpA8zsyiHwWekpZlXvGJvZVZTxQLxB2zZsyoedAJtXWe3Rod69D8g5c0+xpXPttI8aw0QHqNlEfOAq2/MJWQFhoKwcpuY3qt9HVRRKbIRF19+MAW/oHWRqdRcpfoTKWIyDySvoODpcCzcPWLMpDBbRBKGkzPboYCRYXjeuDjBcYyoSa39h4CCZUr3uYcM+f9LirUSie4Rqwu1Y8kGcDuXTAYD0sz6UYEMpnf+NSQDtrklHX3qjpc5AuzblVKs/bduPyTr03rJVYP8GXm2Ta17YCirFWKw/w2Nh/ljNAYXy7HI3BIMh1var0n+0Td3IGzqZUdC03p0jZIms=
    - secure: cgHYZM4vloGgxafoaRYNZggJk383HWXDHBo/9DKWa1/oOAz0vne6o8URus/dwnijd6EwQ6z21BymubmDT4Fa1WEr5+n1jCv5JBFiXq36Ly1pAZi4aSvvHN5cFiZgekNvhR83maNywqTfCGKVDhkPhaiwi8KrwKsqNO4bTm2qG3K0sMcIZ4f/R6szzci5w+oguSIMn3JR26QI0g09HU+/xTte/X6+jmcQGxZPtR3CTL04+LKvZtM02wIUETWOUKJTVH98MjJ5JxwlRCbQRE821Ey+VSyrxE/wnP5jHSGZFaPOgZ3GDBd/mqSf359mEvMoWB1kihOC3CPZRHPe0eNN/KhGG7Be4vL8YDDroVdiO0A5LujlzAyPvHbsBSwMNlH5VHcUyONR5PArcRzEa9WfL0nnVeMBbMZqR0+QuzDFbmDDaMb00xhbABAnpNV1fy4aCrmnOFRR5u1xMrk4sqL8lfGQeU2tsn9V7BjxHHJKcUntKJoQxCs/HQJO9UC70jVKCA5sj1+8xpsfFCgNEMu0vQbyiSH/FjOA5JLYRQNZjzCm+LvFRchu1FXL6W5hF9yFkMUmqIpog4oDYoQbEbBuhjqvhIGSpcvW5pEIH314/iGtUIE4O+8FVS5Q9JVGwq5KXMXFP4tm5udaZ8bjrwDWt9mx6WmSOwaitdkFjJNTWtQ=
notifications:
  slack:
    secure: KO4NG+slaqtFbK5T2FpkR8vgUPfZA5nf+oGDhOCFQXwfcEje/auWKdbSEzCMJ8RMl039wYjtz5iyN6bumD5FYuZFXAddeRiCtaIVqr/r6A536ldneQFTiieyeOYKJkh42hahjstcAKCv0mWr1GZGFc2cyNaoSZvE8/LNcOZy3Rne3ZPAgNMVKF3xkYFUzQOQLJsMEq7sW8LX+Z9zO+OAGjV3uEbiEYlS+N/0VW+ziz+TL+/gNf0rvzAjRd5v/VRudNxuVqx/frpYJzxGS6EHy1vVWFo6NomqBXHQvaEY+W+oorND6Jg0VNhJLCXOk2xxx0JZul2GurkQGex9b3UoARLTWarwOC9Vm/IhZ9Tc57H0U8B7Qxyb0KFacXJPeMqb2tPgNC0/wSIX8uLqlyUJnPqiRgII3W2V1YG3bWJssHNqg5F8WbD+kIphr4ghrW//8EZvcgVK/QS/yIXGLqKYygOYajXoHeb+dR0eCvE2b1wGG/EoZlZcaH2q9lE+1hmyli7MAW3aCmpCEoDUFPq5a8fcdDnYiGV5s1TPbPGvOsd2kYmeFnh71po+GgO07c+1QPLAXiW0YO8hzENi6HMcAdqcKMFXFWYD0fMNPSES/HwIFlAW/c1UBdh7KYCpZ4zljLrHyj1CAM8jXWJ7MTbJYsYHFNHA4eWNZotNLYvQgvs=
addons:
  sauce_connect: true