language: node_js
node_js:
- '0.12'
sudo: false
before_script:
- npm install -g gulp
- npm install -g codeclimate-test-reporter
- gem install scss-lint -v 0.38.0
- gulp preprocess
after_script:
- gulp blanket-lcov-reporter
- gulp coveralls
- codeclimate < test/lcov.info
after_success:
- |
  if [ "$TRAVIS_BRANCH" = "master" ]; then
    git config credential.helper "store --file=.git/credentials"
    echo "https://${GH_TOKEN}:@github.com" > .git/credentials
    git config --global user.name "Grommet Community Bot"
    git config --global user.email "asouza@hp.com"
    gulp release:stable
  fi
env:
  global:
  - secure: PyHVZl5R+jeUNyFxFnBir4nu3p/m3nV1OdOSAXmRLkByMnQZ9zRHvxBesG+rhi9GeUbiDabHg+fdsf18+fZQ/mgyeSHsG9noDuViifq9FaP9XUoViJCseH3suHB7PT8UZczudFn7EwYCAK0TL4AlT/cBX/KBIWvO3gsofhx0Cbg=
  - secure: Wzl8mZUJhpzYRopd3ot6gO8b8LW25URMw1c4kdu9tuJzyY/dwWEATHFvOGT6NDe24qzSpGGRRbojdiJrC1nKJL0NkWfCaEgBZ4P4sT1ok0l81oRMl6dKdSGgIy6YZgLQoKIcp9ZKI6XI1mnxh3ONT8dEMV25R/RRbReNknD/VCc=
  - secure: Jby49sgXHDVhe16au905IQ0kmuyCBF1HPSEPKas3H5NN9BSb8QB/L0HMzSE2asFgg8rSjVIiG7pvabA92mdxRlKECtTYyr1HBGMOqsmLg7iQug2csAeVfm4siYZaUoajM9eWwvwSLEank1HxMzRsPVldGfrviqFqzuDqnFNa91S4/hY1BaDluusWa3Y8a+3+4TM2W2xwTWAnBoFGupFMgYaNH31BQ5gqh4tPfgFqOyjU8TCk05/u/4cAA7mevFlDtrmxHfvuDt48WC2kcgSmLR3oCQjC2+9mgW0pR5vpJjPFtiDjUT3dZdlwjCXyp5Kj4bWzPb8zZl1KIF+xfjrUg+18CFa7tqUUHqLSrPSArZZSDKLvK33C4x06nqX9Rf8AngyGvbKcRbBSuqgBoZIoGM4psTGwNMm++X2klwd7twc/andffbqIFFZ8GFIKqT9PTaeFNSnt7H/+AXSEqfIrh8PMtahpDImo7ZxZm4a+RHm0cPDp9eaaTbV3jlnmD0v73Wlx1mf0ObnRAJnLA0PBP5XhJe98Diddl/3XgPDTLwcQRzA2Vqm1rBHCAJnodhdNDzDNSQD85GtP2RANFq0pdDF1SnqzGb9zePXlEBGKsHKvFB2P2to890BMtOOqRTLzj7QpHTfbTxgaT5V9kGlBoXMUbLbuKDFKe7HxwrFMcsU=
notifications:
  slack:
    secure: KO4NG+slaqtFbK5T2FpkR8vgUPfZA5nf+oGDhOCFQXwfcEje/auWKdbSEzCMJ8RMl039wYjtz5iyN6bumD5FYuZFXAddeRiCtaIVqr/r6A536ldneQFTiieyeOYKJkh42hahjstcAKCv0mWr1GZGFc2cyNaoSZvE8/LNcOZy3Rne3ZPAgNMVKF3xkYFUzQOQLJsMEq7sW8LX+Z9zO+OAGjV3uEbiEYlS+N/0VW+ziz+TL+/gNf0rvzAjRd5v/VRudNxuVqx/frpYJzxGS6EHy1vVWFo6NomqBXHQvaEY+W+oorND6Jg0VNhJLCXOk2xxx0JZul2GurkQGex9b3UoARLTWarwOC9Vm/IhZ9Tc57H0U8B7Qxyb0KFacXJPeMqb2tPgNC0/wSIX8uLqlyUJnPqiRgII3W2V1YG3bWJssHNqg5F8WbD+kIphr4ghrW//8EZvcgVK/QS/yIXGLqKYygOYajXoHeb+dR0eCvE2b1wGG/EoZlZcaH2q9lE+1hmyli7MAW3aCmpCEoDUFPq5a8fcdDnYiGV5s1TPbPGvOsd2kYmeFnh71po+GgO07c+1QPLAXiW0YO8hzENi6HMcAdqcKMFXFWYD0fMNPSES/HwIFlAW/c1UBdh7KYCpZ4zljLrHyj1CAM8jXWJ7MTbJYsYHFNHA4eWNZotNLYvQgvs=

