language: node_js
node_js:
- '0.12'
sudo: false
before_script:
- npm install -g gulp
- gem install scss-lint
- gulp preprocess
after_script:
- gulp blanket-lcov-reporter
- gulp coveralls
after_success:
- |
  if [ "$TRAVIS_BRANCH" = "master" ]; then
    git config credential.helper "store --file=.git/credentials"
    echo "https://${GH_TOKEN}:@github.com" > .git/credentials
    git config --global user.name "grommet-github-bot"
    git config --global user.email "uxgroup@hp.com"
    gulp release:stable
  fi
notifications:
  slack:
    secure: WeOy0cWkkmem1I9eahruJYQLpTy/Qz8A/CNErCnEkOrhItD3SE75jTq49SBT+/VxcVGZaaOqRgzOd/ISjdhEWZOouNI0+lSd4YDFGAZtV9esoJKW4e+xcSciPC9TeUGXrl45bJkFPeVKc1KHoDuqeyBj7E3KmPqyl5AL9xICMmM=
env:
  global:
    secure: PyHVZl5R+jeUNyFxFnBir4nu3p/m3nV1OdOSAXmRLkByMnQZ9zRHvxBesG+rhi9GeUbiDabHg+fdsf18+fZQ/mgyeSHsG9noDuViifq9FaP9XUoViJCseH3suHB7PT8UZczudFn7EwYCAK0TL4AlT/cBX/KBIWvO3gsofhx0Cbg=
